# Use official Node.js runtime as base image
FROM node:20-alpine

#> Set the working directory
WORKDIR /app

# Update Alpine packages
RUN apk update && apk upgrade

#> Copy package.json and package-lock.json
COPY package.json package-lock.json ./

#> Install dependencies
RUN npm install 

#> Copy the rest of the application code
COPY . .

#> Expose the port the app runs on
EXPOSE 8080

#> Start the application
CMD ["npm", "start"]
